Repository DEPthes/4th-MVP-ARTORY-Web, pull requests merged in 2025-08, with the labels that each got.

#8 [Style/#7] 프로필 페이지 버튼 컴포넌트 구현
  src/assets/bannerEdit.svg
  src/assets/bannerReset.svg
  src/assets/fieldCheck.svg
  src/assets/fieldEdit.svg
  src/assets/fieldPlus.svg
  src/assets/images/Banner.png
  src/components/Button/BannerControl.stories.tsx
  src/components/Button/BannerControl.tsx
  src/components/Button/ProfileFieldEdit.stories.tsx
  src/components/Button/ProfileFieldEdit.tsx
  src/components/Button/UserActionButton.tsx
  src/index.css
  tailwind.config.js
Labels: 💄 Style

#14 feat: Header 컴포넌트를 HomePage에 추가
  src/components/Layouts/Header.tsx
  src/components/index.ts
  src/pages/HomePage.tsx
Labels: ✨ Feat

#27 style: 아무것도 없을 때 메시지 위치 조정
  src/pages/ProfilePage.tsx
Labels: 💄 Style, 🔨 Refactor

#30 feat: 가이드 페이지 제작
  package-lock.json
  package.json
  src/components/InfoCard.tsx
  src/pages/HomePage.tsx
  src/pages/SignupJobPage.tsx
  src/pages/SignupProfilePage.tsx
  src/utils/mockAuth.ts
Labels: ✨ Feat

#32 31 feat 사이드바 메뉴 작가노트 페이지 제작
  src/components/Layouts/Header.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/TabMenu.tsx
  src/components/Profile/TagFilterBar.tsx
  src/configs/routes.tsx
  src/pages/ArtistDetailPage.tsx
  src/pages/ArtistNotePage.tsx
  src/pages/ProfilePage.tsx
Labels: ✨ Feat

#36 feat: Input 컴포넌트의 label 속성 선택적 변경 및 Header 검색 기능 개선
  src/components/Input/Input.tsx
  src/components/Layouts/Header.tsx
  src/configs/routes.tsx
  src/pages/SearchResultPage.tsx
Labels: ✨ Feat

#41 [Style/#38] 작가노트 상세페이지 수정
  src/components/ArtworkCard.tsx
  src/components/NoteField/EntryRow.tsx
  src/components/Profile/DisplayEntry.tsx
  src/components/Profile/UserTabInfo.tsx
  src/pages/ArtistDetailPage.tsx
  src/pages/ProfilePage.tsx
Labels: 💄 Style, 🔨 Refactor

#55 [Feat/#52] 게시물 등록수정 페이지 제작
  index.html
  src/assets/imgPlus.svg
  src/components/Chip.tsx
  src/components/Form/ImageUploader.tsx
  src/components/Form/TagSelector.tsx
  src/components/Form/TextArea.tsx
  src/components/Form/TextInput.tsx
  src/components/Layouts/BackNavigate.tsx
  src/configs/routes.tsx
  src/pages/PostEditorPage.tsx
  src/pages/ProfilePage.tsx
  src/types/post.ts
Labels: ✨ Feat, 🔨 Refactor
